Do NOT tag the T0 Routers
- It's not necessary
- It can cause downtime if a T0 router is tagged with the magic string
  `ncp/cluster`
- The screenshot (deleted with the PR) shows an older screenshot with
  the following information:
  - scope: **ncp/cluster**
  - tag: **pcf-fd1**
- Note that it's okay to for a T0 Router to have the scope
  `ncp/cluster`, but it cannot have that as a tag
- It's easy to mistakenly tag the T0 Router with the tag (not scope) of
  `ncp/cluster` because NSX-T managers v2.2 and newer have swapped the
  scope and tag columns
- It will cause PAS deployments to fail when attempting to run the
  notification errand
- Failure symptoms:
  - The `ncp` daemon continues to cycle, and fails with the following
    stack trace:
```
Traceback (most recent call last):
  File "/usr/local/bin/ncp", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/nsx_ujo/cmd/ncp.py", line 16, in main
    ncp_main.start_ncp(coe)
  File "/usr/local/lib/python2.7/dist-packages/nsx_ujo/ncp/main.py", line 124, in start_ncp
    cache.CoeNSXMapping().initialize_cache()
  File "/usr/local/lib/python2.7/dist-packages/nsx_ujo/ncp/nsx/cache.py", line 1270, in initialize_cache
    self._populate_logical_routers(logical_routers)
  File "/usr/local/lib/python2.7/dist-packages/nsx_ujo/ncp/nsx/cache.py", line 288, in _populate_logical_routers
    project_key = tags[self._adaptor.get_project_tag_scope()]
KeyError: 'ncp/cf_org_guid'
```

[#164716252](https://www.pivotaltracker.com/story/show/164716252)